-- FollowCheck V3 - Esquema Maestro Consolidado Supabase con RLS
-- Ejecutar en el SQL Editor de Supabase si es necesario

-- 1. Tabla de Snapshots (Seguidores y Seguidos)
create table if not exists public.snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  followers_count integer not null default 0,
  following_count integer not null default 0,
  followers jsonb not null default '[]'::jsonb,
  following jsonb not null default '[]'::jsonb
);

-- 2. Tabla de Historial de Actividad (Altas y Bajas)
create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  username text not null,
  type text not null check (type in ('followed','unfollowed'))
);

-- 3. Tabla de Preferencias y Clasificación de Cuentas
create table if not exists public.account_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  account_group text not null default 'normal',
  unavailable_reason text default null,
  famous boolean not null default false,
  famous_source text check (famous_source in ('manual', 'auto')),
  ignored boolean not null default false,
  deleted boolean not null default false,
  auto_famous_confidence numeric not null default 0,
  auto_famous_reason text default '',
  auto_famous_checked_at timestamptz,
  auto_famous_dismissed boolean not null default false,
  note text not null default '',
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_account_preference unique (user_id, username)
);

-- Asegurar columnas si la tabla ya existía
alter table public.account_preferences add column if not exists account_group text default 'normal' not null;
alter table public.account_preferences add column if not exists unavailable_reason text default null;

-- 4. Tabla de Perfil de Usuario
create table if not exists public.user_profile (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references auth.users(id) on delete cascade unique,
  instagram_username text,
  display_name text,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null
);

-- 5. Tabla de Subcategorías Personalizadas
create table if not exists public.categories (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  sort_order int default 0 not null,
  created_at timestamptz default now() not null,
  updated_at timestamptz default now() not null,
  unique (user_id, name)
);

-- 6. Tabla de Asignaciones de Cuentas a Subcategorías (Memberships)
create table if not exists public.account_category_memberships (
  id uuid default gen_random_uuid() primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  category_id uuid not null references public.categories(id) on delete cascade,
  created_at timestamptz default now() not null,
  unique (user_id, username, category_id)
);

-- Habilitar RLS en todas las tablas
alter table public.snapshots enable row level security;
alter table public.activity enable row level security;
alter table public.account_preferences enable row level security;
alter table public.user_profile enable row level security;
alter table public.categories enable row level security;
alter table public.account_category_memberships enable row level security;

-- Políticas RLS: Snapshots
drop policy if exists "snapshots_select_own" on public.snapshots;
create policy "snapshots_select_own" on public.snapshots for select using (auth.uid() = user_id);
drop policy if exists "snapshots_insert_own" on public.snapshots;
create policy "snapshots_insert_own" on public.snapshots for insert with check (auth.uid() = user_id);
drop policy if exists "snapshots_delete_own" on public.snapshots;
create policy "snapshots_delete_own" on public.snapshots for delete using (auth.uid() = user_id);

-- Políticas RLS: Activity
drop policy if exists "activity_select_own" on public.activity;
create policy "activity_select_own" on public.activity for select using (auth.uid() = user_id);
drop policy if exists "activity_insert_own" on public.activity;
create policy "activity_insert_own" on public.activity for insert with check (auth.uid() = user_id);
drop policy if exists "activity_delete_own" on public.activity;
create policy "activity_delete_own" on public.activity for delete using (auth.uid() = user_id);

-- Políticas RLS: Account Preferences
drop policy if exists "account_preferences_select_own" on public.account_preferences;
create policy "account_preferences_select_own" on public.account_preferences for select using (auth.uid() = user_id);
drop policy if exists "account_preferences_insert_own" on public.account_preferences;
create policy "account_preferences_insert_own" on public.account_preferences for insert with check (auth.uid() = user_id);
drop policy if exists "account_preferences_update_own" on public.account_preferences;
create policy "account_preferences_update_own" on public.account_preferences for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "account_preferences_delete_own" on public.account_preferences;
create policy "account_preferences_delete_own" on public.account_preferences for delete using (auth.uid() = user_id);

-- Políticas RLS: User Profile
drop policy if exists "user_profile_select" on public.user_profile;
create policy "user_profile_select" on public.user_profile for select using (auth.uid() = user_id);
drop policy if exists "user_profile_insert" on public.user_profile;
create policy "user_profile_insert" on public.user_profile for insert with check (auth.uid() = user_id);
drop policy if exists "user_profile_update" on public.user_profile;
create policy "user_profile_update" on public.user_profile for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "user_profile_delete" on public.user_profile;
create policy "user_profile_delete" on public.user_profile for delete using (auth.uid() = user_id);

-- Políticas RLS: Categories
drop policy if exists "categories_select" on public.categories;
create policy "categories_select" on public.categories for select using (auth.uid() = user_id);
drop policy if exists "categories_insert" on public.categories;
create policy "categories_insert" on public.categories for insert with check (auth.uid() = user_id);
drop policy if exists "categories_update" on public.categories;
create policy "categories_update" on public.categories for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "categories_delete" on public.categories;
create policy "categories_delete" on public.categories for delete using (auth.uid() = user_id);

-- Políticas RLS: Account Category Memberships
drop policy if exists "account_category_memberships_select" on public.account_category_memberships;
create policy "account_category_memberships_select" on public.account_category_memberships for select using (auth.uid() = user_id);
drop policy if exists "account_category_memberships_insert" on public.account_category_memberships;
create policy "account_category_memberships_insert" on public.account_category_memberships for insert with check (auth.uid() = user_id);
drop policy if exists "account_category_memberships_update" on public.account_category_memberships;
create policy "account_category_memberships_update" on public.account_category_memberships for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "account_category_memberships_delete" on public.account_category_memberships;
create policy "account_category_memberships_delete" on public.account_category_memberships for delete using (auth.uid() = user_id);

-- Índices de Rendimiento
create index if not exists idx_snapshots_user_created_at on public.snapshots(user_id, created_at desc);
create index if not exists idx_activity_user_created_at on public.activity(user_id, created_at desc);
create index if not exists idx_account_preferences_user_username on public.account_preferences(user_id, username);
create index if not exists idx_account_preferences_user_updated on public.account_preferences(user_id, updated_at desc);
create index if not exists idx_account_prefs_group on public.account_preferences(user_id, account_group);
create index if not exists idx_categories_user_id on public.categories(user_id);
create index if not exists idx_memberships_user_username on public.account_category_memberships(user_id, username);
create index if not exists idx_memberships_category_id on public.account_category_memberships(category_id);

-- Trigger para auto-confirmar emails
create or replace function public.auto_confirm_user()
returns trigger as $$
begin
  if new.email_confirmed_at is null then
    new.email_confirmed_at := now();
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created_auto_confirm on auth.users;
create trigger on_auth_user_created_auto_confirm
  before insert on auth.users
  for each row execute function public.auto_confirm_user();
