-- FollowCheck V3 - Base de datos consolidada con RLS
create table if not exists public.snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  followers_count integer not null default 0,
  following_count integer not null default 0,
  followers jsonb not null default '[]'::jsonb,
  following jsonb not null default '[]'::jsonb
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  username text not null,
  type text not null check (type in ('followed','unfollowed'))
);

create table if not exists public.account_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  famous boolean not null default false,
  famous_source text check (famous_source in ('manual', 'auto')),
  ignored boolean not null default false,
  deleted boolean not null default false,
  auto_famous_confidence numeric not null default 0,
  auto_famous_reason text default '',
  auto_famous_checked_at timestamptz,
  auto_famous_dismissed boolean not null default false,
  note text not null default '',
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_account_preference unique (user_id, username)
);

alter table public.snapshots enable row level security;
alter table public.activity enable row level security;
alter table public.account_preferences enable row level security;

-- Políticas RLS: Snapshots
create policy "snapshots_select_own"
on public.snapshots for select
using (auth.uid() = user_id);

create policy "snapshots_insert_own"
on public.snapshots for insert
with check (auth.uid() = user_id);

create policy "snapshots_delete_own"
on public.snapshots for delete
using (auth.uid() = user_id);

-- Políticas RLS: Activity
create policy "activity_select_own"
on public.activity for select
using (auth.uid() = user_id);

create policy "activity_insert_own"
on public.activity for insert
with check (auth.uid() = user_id);

create policy "activity_delete_own"
on public.activity for delete
using (auth.uid() = user_id);

-- Políticas RLS: Account Preferences
create policy "account_preferences_select_own"
on public.account_preferences for select
using (auth.uid() = user_id);

create policy "account_preferences_insert_own"
on public.account_preferences for insert
with check (auth.uid() = user_id);

create policy "account_preferences_update_own"
on public.account_preferences for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "account_preferences_delete_own"
on public.account_preferences for delete
using (auth.uid() = user_id);

-- Índices de Rendimiento
create index if not exists idx_snapshots_user_created_at
on public.snapshots(user_id, created_at desc);

create index if not exists idx_activity_user_created_at
on public.activity(user_id, created_at desc);

create index if not exists idx_account_preferences_user_username
on public.account_preferences(user_id, username);

create index if not exists idx_account_preferences_user_updated
on public.account_preferences(user_id, updated_at desc);

-- Trigger para registro directo sin bloqueo por email
create or replace function public.auto_confirm_user()
returns trigger as $$
begin
  if new.email_confirmed_at is null then
    new.email_confirmed_at := now();
  end if;
  return new;
end;
$$ language plpgsql security definer;

drop trigger if exists on_auth_user_created_auto_confirm on auth.users;
create trigger on_auth_user_created_auto_confirm
  before insert on auth.users
  for each row execute function public.auto_confirm_user();
