-- FollowCheck V3 - base segura
create table if not exists public.snapshots (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  followers_count integer not null default 0,
  following_count integer not null default 0,
  followers jsonb not null default '[]'::jsonb,
  following jsonb not null default '[]'::jsonb
);

create table if not exists public.activity (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  username text not null,
  type text not null check (type in ('followed','unfollowed'))
);

alter table public.snapshots enable row level security;
alter table public.activity enable row level security;

create policy "snapshots_select_own"
on public.snapshots for select
using (auth.uid() = user_id);

create policy "snapshots_insert_own"
on public.snapshots for insert
with check (auth.uid() = user_id);

create policy "activity_select_own"
on public.activity for select
using (auth.uid() = user_id);

create policy "activity_insert_own"
on public.activity for insert
with check (auth.uid() = user_id);
