-- FollowCheck V3 - Fase D: Tabla account_preferences para sincronización de clasificaciones con RLS

create table if not exists public.account_preferences (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  username text not null,
  famous boolean not null default false,
  famous_source text check (famous_source in ('manual', 'auto')),
  ignored boolean not null default false,
  deleted boolean not null default false,
  auto_famous_confidence numeric not null default 0,
  auto_famous_reason text default '',
  auto_famous_checked_at timestamptz,
  auto_famous_dismissed boolean not null default false,
  note text not null default '',
  first_seen timestamptz not null default now(),
  last_seen timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_user_account_preference unique (user_id, username)
);

alter table public.account_preferences enable row level security;

create policy "account_preferences_select_own"
on public.account_preferences for select
using (auth.uid() = user_id);

create policy "account_preferences_insert_own"
on public.account_preferences for insert
with check (auth.uid() = user_id);

create policy "account_preferences_update_own"
on public.account_preferences for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "account_preferences_delete_own"
on public.account_preferences for delete
using (auth.uid() = user_id);

create index if not exists idx_account_preferences_user_username
on public.account_preferences(user_id, username);

create index if not exists idx_account_preferences_user_updated
on public.account_preferences(user_id, updated_at desc);
